apiVersion: v1
kind: Service
metadata:
  name: lattice-worker
  labels:
    app.kubernetes.io/name: lattice
    app.kubernetes.io/component: worker
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: lattice
    app.kubernetes.io/component: worker
  ports:
    - name: grpc
      port: 50052
      targetPort: grpc
    - name: metrics
      port: 2113
      targetPort: metrics
