apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lattice.fullname" . }}-table-generator
  labels:
    {{- include "lattice.labels" . | nindent 4 }}
data:
  generate-demo-table.py: |
{{ .Files.Get "files/generate-demo-table.py" | indent 4 }}
