apiVersion: v1
kind: Service
metadata:
  name: {{ include "lattice.fullname" . }}-worker
  labels:
    {{- include "lattice.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "lattice.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: worker
  ports:
    - name: grpc
      port: {{ .Values.worker.grpcPort }}
      targetPort: grpc
    - name: metrics
      port: {{ .Values.worker.metricsPort }}
      targetPort: metrics
